/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpstorage.views;

import ftpstorage.client.Client;
import ftpstorage.client.data.FileSession;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

/**
 *
 * @author HP Zbook 15
 */
public class FileStatus extends javax.swing.JPanel {

    FileSession file = null;
    private boolean completed = false;
    private boolean isDownload;

    private boolean selected = false;
    private ArrayList<FileStatusListener> listeners = new ArrayList<>();
//    private Client client;

    /**
     * Creates new form FileStatus
     */
    public FileStatus(String name, long length, boolean isDownload) {
        this.isDownload = isDownload;
        initComponents();
        this.lblFilename.setText(name);
        //this.lblLeft.setText("0/"+length);
        
        if (isDownload) {
            this.lblStatus.setIcon(new ImageIcon("src/resources/Down.png"));
        } else {
            this.lblStatus.setIcon(new ImageIcon("src/resources/Up.png"));
        }
    }
    
    public boolean isDownload(){
        return this.isDownload;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        lblFilename = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        progress1 = new javax.swing.JProgressBar();
        progress2 = new javax.swing.JProgressBar();
        progress3 = new javax.swing.JProgressBar();
        progress4 = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(1210, 36));
        setPreferredSize(new java.awt.Dimension(1210, 36));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Down.png"))); // NOI18N

        lblFilename.setText("a.txt");

        lblLeft.setEnabled(false);

        progress1.setForeground(new java.awt.Color(0, 204, 0));
        progress1.setPreferredSize(new java.awt.Dimension(160, 14));
        progress1.setStringPainted(true);

        progress2.setForeground(new java.awt.Color(0, 204, 0));
        progress2.setPreferredSize(new java.awt.Dimension(160, 14));
        progress2.setStringPainted(true);

        progress3.setForeground(new java.awt.Color(0, 204, 0));
        progress3.setPreferredSize(new java.awt.Dimension(160, 14));
        progress3.setStringPainted(true);

        progress4.setForeground(new java.awt.Color(0, 204, 0));
        progress4.setPreferredSize(new java.awt.Dimension(160, 14));
        progress4.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progress4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFilename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        setSelected(true);
        notifySelected();
    }//GEN-LAST:event_formMouseClicked

    public void setSelected(boolean selected) {
        this.selected = selected;
        if (!selected) {
            this.setBackground(new Color(255, 255, 255));
            this.jPanel1.setBackground(new Color(255, 255, 255));
        } else {
            this.setBackground(new Color(0, 255, 205));
            this.jPanel1.setBackground(new Color(0, 255, 205));
        }
    }

    public boolean isSelected() {
        return this.selected;
    }

    public void addListenner(FileStatusListener listener) {
        this.listeners.add(listener);
    }

    public void notifySelected() {
        for (FileStatusListener ip : listeners) {
            ip.notifySelected(this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFilename;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JProgressBar progress1;
    private javax.swing.JProgressBar progress2;
    private javax.swing.JProgressBar progress3;
    private javax.swing.JProgressBar progress4;
    // End of variables declaration//GEN-END:variables

    public JProgressBar[] getProgressBars() {
        JProgressBar[] tmp = {progress1, progress2, progress3, progress4};
        return tmp;
    }

    void nottifyComplete() {
        this.completed = true;
        this.lblStatus.setIcon(new ImageIcon("src/resources/Ok.png"));
    }

    public boolean isCompleted() {
        return this.completed;
    }

    void pause() {
        this.lblStatus.setIcon(new ImageIcon("src/resources/Pause.png"));
    }

    void resume() {
        if (isDownload) {
            this.lblStatus.setIcon(new ImageIcon("src/resources/Down.png"));
        } else {
            this.lblStatus.setIcon(new ImageIcon("src/resources/Up.png"));
        }
        
//        if(client != null){
//            client.get(TOOL_TIP_TEXT_KEY, offsets, fileToSave)
//        }
    }

    void delete() {
//        System.out.println("delete file status ui");
        this.jPanel1.removeAll();
    }

//    public void setClient(Client client) {
//        this.client = client;
//    }
}

